import { useQuery } from '@tanstack/react-query';
import { formatDistanceToNow } from 'date-fns';
import { Radio, AlertTriangle, PlayCircle } from 'lucide-react';
import api from '../api/client';
import SeverityBadge from '../components/SeverityBadge';

export default function NarratorPage() {
  const { data: logs = [], refetch, isFetching } = useQuery({
    queryKey: ['narrator-logs'],
    queryFn: () => api.get('/api/narrator/logs').then(res => res.data),
    refetchInterval: 5000,
  });

  const handleTestBroadcast = async () => {
    try {
      await api.post('/api/narrator/broadcast-test');
      refetch();
    } catch (e) {
      console.error('Failed to trigger test broadcast', e);
    }
  };

  return (
    <div className="flex flex-col h-full bg-slate-50">
      <div className="bg-white border-b border-slate-200 px-8 py-6 shrink-0 flex items-center justify-between shadow-sm">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-3">
            <Radio className="w-7 h-7 text-indigo-500" />
            AI Safety Narrator Feed
          </h1>
          <p className="mt-1 text-sm text-slate-500">Live, natural-language emergency broadcasts generated by Gemini 2.5.</p>
        </div>
        <button
          onClick={handleTestBroadcast}
          disabled={isFetching}
          className="flex items-center gap-2 rounded-md bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 disabled:opacity-50 transition-colors"
        >
          <PlayCircle className="w-5 h-5" />
          Trigger Auto-Broadcast Demo
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-8">
        <div className="max-w-4xl mx-auto space-y-6">
          {logs.map((log) => (
            <div key={log.id} className="bg-white group rounded-xl shadow-sm border border-slate-200 p-6 transition-all hover:shadow-md hover:border-indigo-200">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                  <span className="flex h-3 w-3 relative">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                    <span className="relative inline-flex rounded-full h-3 w-3 bg-red-500"></span>
                  </span>
                  <SeverityBadge severity={log.severity} />
                  <span className="text-sm font-semibold text-slate-700 uppercase tracking-wider">{log.incident_type}</span>
                </div>
                <time className="text-sm text-slate-500 font-medium whitespace-nowrap">
                  {formatDistanceToNow(new Date(log.broadcast_at), { addSuffix: true })}
                </time>
              </div>
              
              <div className="bg-slate-50 rounded-lg p-5 border border-slate-100 relative">
                <div className="absolute -left-3 -top-3 p-2 bg-indigo-100 rounded-full border-4 border-white">
                  <AlertTriangle className="w-4 h-4 text-indigo-600" />
                </div>
                <p className="text-slate-800 text-lg leading-relaxed font-medium mb-3">
                  "{log.narrative}"
                </p>
                <div className="flex items-center justify-between border-t border-slate-200 pt-3 mt-2">
                  <span className="text-xs font-mono text-slate-400 bg-white px-2 py-1 rounded border border-slate-100">
                    ID: {log.id} • Ref: INC_{log.incident_id || 'DEMO'}
                  </span>
                  <span className="text-xs font-bold text-transparent bg-clip-text bg-gradient-to-r from-teal-500 to-blue-600">
                    Powered by Gemini Flash 2.5
                  </span>
                </div>
              </div>
            </div>
          ))}

          {logs.length === 0 && (
            <div className="text-center py-20 bg-white rounded-xl border border-slate-200 border-dashed">
              <Radio className="mx-auto h-12 w-12 text-slate-300" />
              <h3 className="mt-2 text-sm font-semibold text-slate-900">No broadcasts</h3>
              <p className="mt-1 text-sm text-slate-500">The narrator feed is currently clear.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
